-- tsuki PostgreSQL init script
-- Usage:
--   psql -d tsuki -f code/be/tsuki-api/scripts/db/init_tsuki_db.sql

CREATE TABLE IF NOT EXISTS tsuki_main (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kanji TEXT NOT NULL,
  hiragana TEXT NOT NULL,
  sentence TEXT NOT NULL,
  tokens TEXT NOT NULL,
  updated INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tsuki_mean (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id INTEGER NOT NULL,
  lang TEXT NOT NULL,
  mean_w TEXT NOT NULL,
  mean_s TEXT NOT NULL,
  updated INTEGER NOT NULL,
  CONSTRAINT fk_tsuki_mean_word
    FOREIGN KEY (word_id) REFERENCES tsuki_main(id) ON DELETE CASCADE,
  CONSTRAINT chk_tsuki_mean_lang
    CHECK (lang IN ('cn', 'tw', 'en', 'ja')),
  CONSTRAINT uq_tsuki_mean_word_lang
    UNIQUE (word_id, lang)
);

CREATE TABLE IF NOT EXISTS tsuki_seek (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word_id INTEGER NOT NULL,
  lang TEXT NOT NULL,
  term TEXT NOT NULL,
  updated INTEGER NOT NULL,
  CONSTRAINT fk_tsuki_seek_word
    FOREIGN KEY (word_id) REFERENCES tsuki_main(id) ON DELETE CASCADE,
  CONSTRAINT chk_tsuki_seek_lang
    CHECK (lang IN ('cn', 'tw', 'en', 'ja')),
  CONSTRAINT uq_tsuki_seek_word_lang_term
    UNIQUE (word_id, lang, term)
);
