spring:
  application:
    name: tsuki-api
  datasource:
    url: jdbc:postgresql://localhost:5432/tsuki
    username: umineko
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 5188
